### ISSUE TITLE
Upgrade arb bot to work with Orderbook V4

### ISSUE THREAD

**Issue by hardyjosh** [rainlanguage/arb-bot#141]
We are upgrading to Orderbook V4 across the Raindex stack.

We need the arb bot to be compatible.

@rouzwelt pls list here the steps required to get there.

edit:

Starting a task list to track the required changes:
- [x] Update obv4 ABI, modify vaultBalance() call: #142 
- [x] Update arb contract ABI and make required changes: #142 
- [x] Subgraph queries for fetching new orders: #142 
- [x] Delete old dead codes (contract artifacts, test utils, etc): #142 
- [x] Update e2e and unit tests to be compatible with V4: #142 
- [x] New deployments (OrderbookV4, RouteProcessorV4ArbObV4): see below
- [x] Deploy subgraphs for deployed Orderbook on each network: see below
- [x] prod test on a chain (include link to a cleared tx): https://basescan.org/tx/0x17610167bdce9b5749b3bdbda17a0a7d0b0d9869bdb0cd885ebca551550cd809
https://basescan.org/tx/0x5dc0424b5ace0fe6249399065b8c1ecb8427f1731eee4e2ed8643dbfe580ba46

### Deployments:
- [x] base:
  - OrderbookV4: 0xA2f56F8F74B7d04d61f281BE6576b6155581dcBA
  - RainterpreterParserNPE2: 0xF836f2746B407136a5bCB515495949B1edB75184
  - RainterpreterStoreNPE2: 0x6E4b01603edBDa617002A077420E98C86595748E
  - RainterpreterNPE2: 0x379b966DC6B117dD47b5Fc5308534256a4Ab1BCC
  - RainterpreterExpressionDeployerNPE2: 0x56394785a22b3BE25470a0e03eD9E0a939C47b9b
  - RPV4Arb: 0xF97A86C2Cb3e42f89AC5f5AA020E5c3505015a88
  - sg: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-base/0.1/gn

**Comment by rouzwelt** [comment]
> We are upgrading to Orderbook V4 across the Raindex stack.
> 
> We need the arb bot to be compatible.
> 
> @rouzwelt pls list here the steps required to get there.

steps for updating to any ob version requires only to set up the new ABI for vaultBalance()
and as well as any changes with arb contract arb() method abi, as well as upading the values passed to theose methods to correctly match the new ABI

**Comment by hardyjosh** [comment]
@rouzwelt there is also a new subgraph so the way orders are queried has changed

do we need a new arb contract?

**Comment by rouzwelt** [comment]
> @rouzwelt there is also a new subgraph so the way orders are queried has changed
> 
> do we need a new arb contract?

ok so then we nee to update the sg query, and for arb contracts, yes ofc we nees new deployments

**Comment by rouzwelt** [comment]
todo:

- [ ] - update sg queries
- [ ] - update ob abi
- [ ] - update arb abi and piece of code that builds fn data for making an arb() tx
- [ ] - update tests with deployed obv4 and arb contracts rather than deploying them on tests

PS: small stuff might come up duting implementation, so lets allow some room for that, but these tasks are small enough to fit into 1 PR altogether, or sep PRs for each, though sep PR would break the tests until all pieces are implemented.

**Comment by hardyjosh** [comment]
closing this as #142 is merged
