### ISSUE TITLE
Orders can clear against orders on a different Orderbook

### ISSUE THREAD

**Issue by hardyjosh** [rainlanguage/arb-bot#148]
The arb bot will currently clear against other AMMs supported by the RouteProcessor contract.

https://github.com/rainlanguage/arb-bot/issues/147 refers to orders clearing against other orders on the same orderbook.

NOTE: the first step is to have the result of #150 , once that is known, we can start to prepare a plan fir this ticket.

This issue is for orders clearing against orders on other orderbooks, on the same network.

Edit1: spike showed we can use `GenericArbOrderTaker` contract with encoded `takeOrders2()` to perform inter-ob clears.

Edit2: As discussed in group chat, we will use ob crate cli for quoting, so implementation plan will be prepared and written once the ob quoting cli is ready. (can be followed here: https://github.com/rainlanguage/rain.orderbook/issues/709)

---

### implementation plan:
- [x] - implement a quoting logic for array of orders with multicall, uses orderbook quote wasm/js
- [x] - implement logic that dryruns the `arb2()` of `GenericArbOrderTaker` with encoded `takeOrders2()` and see if it passes, this would need correct setting of maxInput for both arb2() and encoded takeOrders2() with the quote results.
- [x] - a logic to compare the result against the RP4 clearing case and pick the best one
- [x] - possibly some refactor to allow for above logic to be integerated into the app's main logic
